"""
Report Formatter Module

Formats reports in multiple output formats: JSON, HTML, PDF, Excel, Markdown, Plain Text
"""

from typing import Dict, Any, Optional
from enum import Enum
import json
from datetime import datetime
from .report_generator import ExecutiveReport, ReportSection


class OutputFormat(str, Enum):
    """Supported output formats."""
    JSON = "json"
    HTML = "html"
    MARKDOWN = "markdown"
    TEXT = "text"
    CSV = "csv"
    EXCEL = "excel"
    PDF = "pdf"


class ReportFormatter:
    """Format reports for various output targets."""
    
    def __init__(self):
        """Initialize formatter."""
        self.formatters = {
            OutputFormat.JSON: self._format_json,
            OutputFormat.HTML: self._format_html,
            OutputFormat.MARKDOWN: self._format_markdown,
            OutputFormat.TEXT: self._format_text,
            OutputFormat.CSV: self._format_csv,
            OutputFormat.EXCEL: self._format_excel,
            OutputFormat.PDF: self._format_pdf,
        }
    
    def format(self, report: ExecutiveReport, output_format: OutputFormat) -> str:
        """Format report to specified output format."""
        formatter = self.formatters.get(output_format)
        if not formatter:
            raise ValueError(f"Unsupported format: {output_format}")
        return formatter(report)
    
    def _format_json(self, report: ExecutiveReport) -> str:
        """Format report as JSON."""
        return json.dumps(report.to_dict(), indent=2, default=str)
    
    def _format_html(self, report: ExecutiveReport) -> str:
        """Format report as HTML."""
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{report.title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; line-height: 1.6; }}
        .header {{ background-color: #2c3e50; color: white; padding: 20px; }}
        .title {{ font-size: 28px; font-weight: bold; }}
        .meta {{ font-size: 12px; margin-top: 10px; }}
        .summary {{ background-color: #ecf0f1; padding: 15px; margin: 20px 0; border-left: 4px solid #3498db; }}
        .section {{ margin: 30px 0; }}
        .section-title {{ font-size: 20px; font-weight: bold; color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        .metric {{ display: inline-block; margin: 10px 20px 10px 0; padding: 10px; background-color: #f8f9fa; border-radius: 5px; }}
        .metric-value {{ font-size: 24px; font-weight: bold; color: #27ae60; }}
        .metric-label {{ font-size: 12px; color: #7f8c8d; }}
        .recommendation {{ background-color: #fff3cd; padding: 10px; margin: 10px 0; border-left: 4px solid #ffc107; }}
        .risk {{ background-color: #f8d7da; padding: 10px; margin: 10px 0; border-left: 4px solid #dc3545; }}
        .opportunity {{ background-color: #d1ecf1; padding: 10px; margin: 10px 0; border-left: 4px solid #17a2b8; }}
        table {{ width: 100%; border-collapse: collapse; margin: 15px 0; }}
        th, td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #ecf0f1; font-weight: bold; }}
        tr:hover {{ background-color: #f5f5f5; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #7f8c8d; }}
    </style>
</head>
<body>
    <div class="header">
        <div class="title">{report.title}</div>
        <div class="meta">
            Report ID: {report.metadata.report_id} | Generated: {report.metadata.generated_at.strftime('%Y-%m-%d %H:%M:%S')}
        </div>
    </div>
    
    <div class="summary">
        <h3>Executive Summary</h3>
        <p>{report.summary}</p>
    </div>
    
    <div class="section">
        <div class="section-title">Key Metrics</div>
        {self._html_metrics(report.key_metrics)}
    </div>
"""
        
        for section in report.sections:
            html += self._html_section(section)
        
        if report.recommendations:
            html += f"""
    <div class="section">
        <div class="section-title">Recommendations</div>
        {self._html_recommendations(report.recommendations)}
    </div>
"""
        
        html += f"""
    <div class="footer">
        <p>This report was automatically generated by the Autonomous Report Engine.</p>
        <p>Data sources: {', '.join(report.metadata.data_sources)}</p>
        <p>Confidence score: {report.metadata.confidence_score * 100:.0f}%</p>
    </div>
</body>
</html>
"""
        return html
    
    def _format_markdown(self, report: ExecutiveReport) -> str:
        """Format report as Markdown."""
        md = f"""# {report.title}

**Report ID:** {report.metadata.report_id}  
**Generated:** {report.metadata.generated_at.strftime('%Y-%m-%d %H:%M:%S')}  
**Report Type:** {report.metadata.report_type.value}  
**Status:** {report.metadata.status.value}

## Executive Summary

{report.summary}

## Key Metrics

| Metric | Value |
|--------|-------|
"""
        
        for key, value in report.key_metrics.items():
            metric_display = f"${value:,.0f}" if isinstance(value, (int, float)) and "value" in key.lower() else str(value)
            md += f"| {key.replace('_', ' ').title()} | {metric_display} |\n"
        
        md += "\n"
        
        for section in report.sections:
            md += self._markdown_section(section)
        
        if report.recommendations:
            md += "## Recommendations\n\n"
            for i, rec in enumerate(report.recommendations, 1):
                md += f"### {i}. {rec.get('title', 'Recommendation')}\n"
                md += f"- **Priority:** {rec.get('priority', 'N/A')}\n"
                md += f"- **Description:** {rec.get('description', '')}\n"
                md += f"- **Timeline:** {rec.get('timeline', '')}\n"
                md += f"- **Impact:** {rec.get('expected_impact', '')}\n\n"
        
        md += f"""
---
**Metadata**
- **Data Sources:** {', '.join(report.metadata.data_sources)}
- **Confidence:** {report.metadata.confidence_score * 100:.0f}%
- **Period:** {report.metadata.period_start.strftime('%Y-%m-%d')} to {report.metadata.period_end.strftime('%Y-%m-%d')}
"""
        return md
    
    def _format_text(self, report: ExecutiveReport) -> str:
        """Format report as plain text."""
        txt = f"""
{'='*80}
{report.title}
{'='*80}

Report ID: {report.metadata.report_id}
Generated: {report.metadata.generated_at.strftime('%Y-%m-%d %H:%M:%S')}
Report Type: {report.metadata.report_type.value}
Status: {report.metadata.status.value}

{'-'*80}
EXECUTIVE SUMMARY
{'-'*80}

{report.summary}

{'-'*80}
KEY METRICS
{'-'*80}

"""
        
        for key, value in report.key_metrics.items():
            metric_display = f"${value:,.0f}" if isinstance(value, (int, float)) and "value" in key.lower() else str(value)
            txt += f"{key.replace('_', ' ').title()}: {metric_display}\n"
        
        txt += f"\n{'-'*80}\n"
        
        for section in report.sections:
            txt += self._text_section(section)
        
        if report.recommendations:
            txt += f"\n{'-'*80}\nRECOMMENDATIONS\n{'-'*80}\n\n"
            for i, rec in enumerate(report.recommendations, 1):
                txt += f"{i}. {rec.get('title', 'Recommendation')}\n"
                txt += f"   Priority: {rec.get('priority', 'N/A')}\n"
                txt += f"   Description: {rec.get('description', '')}\n"
                txt += f"   Timeline: {rec.get('timeline', '')}\n"
                txt += f"   Impact: {rec.get('expected_impact', '')}\n\n"
        
        txt += f"""
{'-'*80}
METADATA
{'-'*80}

Data Sources: {', '.join(report.metadata.data_sources)}
Confidence: {report.metadata.confidence_score * 100:.0f}%
Period: {report.metadata.period_start.strftime('%Y-%m-%d')} to {report.metadata.period_end.strftime('%Y-%m-%d')}
Tags: {', '.join(report.metadata.tags)}

{'='*80}
"""
        return txt
    
    def _format_csv(self, report: ExecutiveReport) -> str:
        """Format report as CSV."""
        csv = "Metric,Value\n"
        
        for key, value in report.key_metrics.items():
            metric_display = f"${value:,.0f}" if isinstance(value, (int, float)) and "value" in key.lower() else str(value)
            csv += f'"{key.replace("_", " ").title()}","{metric_display}"\n'
        
        return csv
    
    def _format_excel(self, report: ExecutiveReport) -> str:
        """Format report as Excel-compatible data."""
        # This would require additional libraries (openpyxl, xlsxwriter)
        # Return JSON representation for Excel data
        return json.dumps({
            'title': report.title,
            'metadata': {
                'report_id': report.metadata.report_id,
                'generated_at': report.metadata.generated_at.isoformat(),
            },
            'metrics': report.key_metrics,
            'recommendations': report.recommendations,
        }, indent=2, default=str)
    
    def _format_pdf(self, report: ExecutiveReport) -> str:
        """Format report as PDF-ready data."""
        # This would require additional libraries (reportlab, weasyprint)
        # Return HTML as intermediate format
        return self._format_html(report)
    
    # Helper methods
    
    def _html_metrics(self, metrics: Dict[str, Any]) -> str:
        """Generate HTML metrics display."""
        html = ""
        for key, value in metrics.items():
            if isinstance(value, (int, float)) and "value" in key.lower():
                display = f"${value:,.0f}"
            else:
                display = str(value)
            
            html += f"""
        <div class="metric">
            <div class="metric-value">{display}</div>
            <div class="metric-label">{key.replace('_', ' ').title()}</div>
        </div>
"""
        return html
    
    def _html_section(self, section: ReportSection) -> str:
        """Generate HTML section."""
        html = f"""
    <div class="section">
        <div class="section-title">{section.title}</div>
        <p>{section.content}</p>
"""
        
        for subsection in section.subsections:
            html += f"""
        <div style="margin-left: 20px;">
            <h4>{subsection.title}</h4>
            <p>{subsection.content}</p>
        </div>
"""
        
        html += "    </div>\n"
        return html
    
    def _html_recommendations(self, recommendations: list) -> str:
        """Generate HTML recommendations."""
        html = ""
        for rec in recommendations:
            html += f"""
        <div class="recommendation">
            <strong>{rec.get('title', 'Recommendation')}</strong> (Priority: {rec.get('priority', 'N/A')})
            <p>{rec.get('description', '')}</p>
            <small>Timeline: {rec.get('timeline', '')} | Impact: {rec.get('expected_impact', '')}</small>
        </div>
"""
        return html
    
    def _markdown_section(self, section: ReportSection) -> str:
        """Generate Markdown section."""
        md = f"\n## {section.title}\n\n{section.content}\n"
        
        for subsection in section.subsections:
            md += f"\n### {subsection.title}\n\n{subsection.content}\n"
        
        return md
    
    def _text_section(self, section: ReportSection) -> str:
        """Generate text section."""
        txt = f"\n{section.title.upper()}\n{'-' * len(section.title)}\n\n{section.content}\n"
        
        for subsection in section.subsections:
            txt += f"\n{subsection.title}\n{'-' * len(subsection.title)}\n{subsection.content}\n"
        
        return txt
    
    def generate_visualization_specs(self, report: ExecutiveReport) -> Dict[str, Any]:
        """Generate visualization specifications for dashboards."""
        return {
            'charts': [
                {
                    'type': 'gauge',
                    'title': 'Health Score',
                    'value': report.key_metrics.get('health_score', 0),
                    'max': 100,
                },
                {
                    'type': 'bar',
                    'title': 'KPI Status',
                    'data': {
                        'on_target': report.key_metrics.get('kpis_on_target', 0),
                        'at_risk': report.key_metrics.get('kpis_at_risk', 0),
                    }
                },
                {
                    'type': 'metric',
                    'title': 'Opportunities',
                    'value': report.key_metrics.get('opportunities_count', 0),
                    'subtext': f"${report.key_metrics.get('total_opportunity_value', 0):,.0f}",
                },
            ],
            'tables': [
                {
                    'title': 'Key Metrics',
                    'columns': ['Metric', 'Value'],
                    'rows': [[k, str(v)] for k, v in report.key_metrics.items()],
                },
            ]
        }
